# BookmarksBundle/config/routing

homepage:
  path: /
  defaults: { _controller: BookmarksBundle:Homepage:dashboard }

bookmarks:
    path: /bookmarks
    defaults: { _controller: BookmarksBundle:Bookmarks:showBookmarks }
    
bookmarks-add-new:
    path: /bookmarks/add/
    defaults: { _controller: BookmarksBundle:Bookmarks:addNewBookmark }