# app/config/routing

test:
    resource: "@BookmarksBundle/Resources/config/routing.yml"
    prefix:   /

yml_routing:
    path: /yml_routing
    defaults: { _controller: AppBundle:YmlRouting:route }
    
lucky_euro_millions:
    path: /lucky/euromillions
    defaults: { _controller: AppBundle:Lucky:euroMillions }
    